services:
  redis:
    container_name: jobsies-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 128M
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 3