[project]
name = "jobsies"
version = "0.1.1"
description = "Run small jobs automatically on your home server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery[redis]>=5.6.3",
    "click>=8.4.2",
    "croniter>=6.2.4",
    "fastapi>=0.141.1",
    "httpx2>=2.10.0",
    "jinja2>=3.1.6",
    "justhtml>=3.10.1",
    "loguru>=0.7.3",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "sqlalchemy>=2.0.51",
    "sqlmodel>=0.0.39",
    "uvicorn>=0.52.3",
]

[project.scripts]
jobsies = "jobsies:main"
populate-db = "jobsies.scripts.populate_db:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "1 week"
exclude-newer-package = { setuptools = "30 days" }

[tool.ruff]
line-length = 120
target-version = "py313" # the python version to target
src = [".", "jobsies"]
show-fixes = true
unsafe-fixes = true

[tool.ruff.format]
docstring-code-format = true

# ignore certain rules for specific files
[tool.ruff.lint.per-file-ignores]
"tests/**.py" = ["S101", "SLF001", "PLR2004"]
"notebooks/**.ipynb" = ["T201"]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN401",
    "COM812",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D203",
    "D205",
    "D211",
    "D212",
    "D401",
    "D405",
    "D406",
    "D407",
    "D408",
    "ERA001",
    "FIX002",
    "ISC001",
    "TD002",
    "TD003",
    "CPY001",
]
